### ISSUE TITLE
Conda installation for MacOs: no bash_profile in home directory

### ISSUE THREAD

**Issue by GravitationalWaveSurfer** [Asterics2020-Obelics/School2018#13]
Hi, I had some issues while trying to follow the installation instructions provided. Firstly, clicking on the "Download" link, my Mac downloads by default in the "Download" folder, while typically the terminal opens in the user home folder **~/**,  therefore a slight adjustment you may have to use in the terminal is:

`Downloads/bash Anaconda3-5.1.0-MacOSX-x86_64.sh`

Secondly, my Mac is of late fall 2017, so the **.bash_profile** does not exist in my home directory (a quick check can be done by `ls -a ~/`). A quick tour on Stackoverflow questions confirms that many new Mac OS do not have a **.bashrc** or **.bash_profile** file by default. If that's the case, simply create it: 

`vi .bash_profile`

and insert (with vi pressing 'i' on keyboard) the suggested line `. "$HOME/.local/anaconda3/etc/profile.d/conda.sh"`.

Also I had to source with `source $HOME/.local/anaconda3/bin/activate`, but @MaxNoe pointed out that should not be done, suggesting I should have `source anaconda/etc/profile.d/conda.sh` followed by `conda activate`. What is the difference involved?

**Comment by maxnoe** [comment]
The former one is the "old way" prior to conda 4.4, the latter should be used with conda >= 4.4.

**Comment by maxnoe** [comment]
>  `source anaconda/etc/profile.d/conda.sh`

This should be `source  "$HOME/.local/anaconda3/etc/profile.d/conda.sh"`, with `anaconda` I meant the anaconda install Path, sorry if that wasn't clear
