### ISSUE TITLE
Update conda to current version

### ISSUE THREAD

**Issue by maxnoe** [Asterics2020-Obelics/School2018#4]
Current version is 5.1

https://repo.anaconda.com/archive/Anaconda3-5.1.0-Linux-x86_64.sh

I would open a PR, but you will also need to change the local copy in your owncloud, where I don't have access. BTW, do you think this is really necesarry? Is the owncloud reachable via LAN at the venue?

**Comment by vincentpoireau** [comment]
Thanks to have spotted this. I removed the local copy links that were not so useful last year, and updated the Anaconda links. I have also copied requirements.txt from last year.
